name: AA-Car_main

on:
  schedule:
    - cron: '*/40 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./-/C.TXT
        
      - name: '公众号iosrule' 
        run: python3 ./-/Car_main.py 
        env:
            DJJ_BARK_COOKIE: ${{ secrets.DJJ_BARK_COOKIE }}
            DJJ_TELE_COOKIE: ${{ secrets.DJJ_TELE_COOKIE }}
            car_url: ${{ secrets.car_url }}
            car_hd: ${{ secrets.car_hd }}
            car_bt0: ${{ secrets.car_bt0 }}
            car_bt1: ${{ secrets.car_bt1 }}
            car_bt2: ${{ secrets.car_bt2 }}
            car_bt3: ${{ secrets.car_bt3 }}
            car_bt4: ${{ secrets.car_bt4 }}
            car_bt5: ${{ secrets.car_bt5 }}
            car_bt6: ${{ secrets.car_bt6 }}
            car_bt7: ${{ secrets.car_bt7 }}
            car_bt8: ${{ secrets.car_bt8 }}
            car_bt9: ${{ secrets.car_bt9 }}
                        
