# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 领京豆额外奖励&抢京豆
# 脚本自带助力码，介意者可将 29行 helpAuthor 变量设置为 false
# 活动入口：京东APP首页-领京豆
# 更新地址：https://gitee.com/lxk0301/jd_scripts/raw/master/jd_bean_home.js
name: 领豆豆额外奖励

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "19 23 * * *"
    workflow_dispatch:
jobs:
  build:
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.JD_COOKIE
        run: |
          git clone https://github.com/New-Sina/king_Zoo.git ~/king_Zoo
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.JD_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.JD_COOKIE
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.JD_COOKIE
        run: |
          cd ~/king_Zoo
          git checkout Yml
          npm install
      - name: "运行 【领豆豆额外奖励】"
        run: |
          cd ~/king_Zoo
          node Ponysitters_Club_Season.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          SYNCURL: /The.Flash/The.Flash/bea0n_h0ome.js
          SCKEY: ${{ secrets.SCKEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          EFORK: ${{ secrets.EFORK }}
          GITHUB: ${{ secrets.GITHUB }}
          
          
